# Generated by Django 2.2.3 on 2019-07-02 23:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('account_number', models.PositiveIntegerField()),
                ('buyer_phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('id_type', models.CharField(choices=[('Biometric Passport', 'Biometric Passport'), ('Drivers License', 'Drivers License'), ('Natinal Health Insurance', 'National Health Insurance'), ('National ID', 'National ID'), ('Voters ID', 'Voters ID')], max_length=10)),
                ('id_number', models.PositiveIntegerField()),
                ('employer', models.CharField(max_length=100)),
                ('payslip', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=100)),
                ('lender_location', models.CharField(max_length=100)),
                ('lender_phonenumber', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('product_unitprice', models.DecimalField(decimal_places=2, max_digits=19)),
                ('product_stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_name', models.CharField(max_length=100)),
                ('retailer_location', models.CharField(max_length=100)),
                ('retailer_account_number', models.IntegerField()),
                ('retailer_phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('retailer_banker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lender')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Retailer')),
            ],
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lender'),
        ),
    ]
